name: CI/CD for Kit-IT Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Linting and testing job
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - run: npm ci

      # Lint the code
      - name: Run ESLint
        run: npm run lint

      # Run tests
      - name: Run Tests
        run: npm test

  # Deployment job (e.g., publishing the package)
  publish-npm:
    needs: lint-and-test  # Ensures linting and tests pass before publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_CUSTOM_TOKEN }}

  # Optional deployment to production (API deployment example)
  deploy-api:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API
        run: |
          echo "Deploying API to production..."
          # Add API deployment commands (e.g., Docker, SSH)
